### ISSUE TITLE
Jupyter Notebook for Ethiopia Data Example

### ISSUE THREAD

**Issue by heikomuller** [VIDA-NYU/openclean-core#30]
Create a notebook for the Ethiopia data example where cleaning is done with openclean.

**Comment by maqzi** [comment]
oops, forgot to mention it here. Created a new repo: [openclean-demos](https://github.com/VIDA-NYU/openclean-demos/) with the [ethiopian notebook](https://github.com/VIDA-NYU/openclean-demos/blob/main/notebooks/Open%20Clean%20demo%20-%20Ethiopian%20data.ipynb).
