### ISSUE TITLE
openclean-core won't install on Python 3.9

### ISSUE THREAD

**Issue by heikomuller** [VIDA-NYU/openclean-core#89]
An error occurs when installing openclean-core (using pip) on Python 3.9 (caused by fuzzyset).

**Comment by maqzi** [comment]
recommended solution: move away from fuzzy set since, fuzzywuzzy achieves the same functionality.

**Comment by maqzi** [comment]
#92 should resolve this. Ended up implementing an adapted version of fuzzyset to avoid the extra dependency.

**Comment by heikomuller** [comment]
Looks like there are other potential issues with Python 3.9 (e.g., [Shapely can also cause issues when installing on macOS](https://github.com/Toblerity/Shapely/issues/1040)).

**Comment by heikomuller** [comment]
Closed by PR #96. I ended up removing the dependency and the only class `` that depended on the package.

I recall from #1 that similar functionality is implemented in [datamart_geo](https://pypi.org/project/datamart-geo/). We may want to consider creating a separate package **openclean-geo** with a collection of cleaning and profiling functions for geospatial data.
